### ISSUE TITLE
There is not "art" in requirements.txt

### ISSUE THREAD

**Issue by LipwFellipe** [imvickykumar999/Multiplayer-Ursina-Game#2]

**Comment by imvickykumar999** [comment]
Yes, you are right.
I used `art` package to print server address in large font, other than that there is no use in this project.

[tprint(server_addr)](https://github.com/imvickykumar999/Multiplayer-Ursina-Game/blob/c95cc21091c3d17893693d737c2b6f02d2c76a7e/server/main.py#L137C5-L137C24)

```py
def main():
    hostname = socket.gethostname()
    server_addr = socket.gethostbyname(hostname)

    print("\nServer started, listening for new connections...")
    print(f'IPV4 Address = {server_addr}\n')

    tprint(server_addr)
```

You can fork to contribute requirements if you wish, I will merge changes.
